### ISSUE TITLE
Please add tutorial, how to run QuestJS

### ISSUE THREAD

**Issue by PerStrateg** [ThePix/QuestJS#13]
Hello! If it possible, please, can you create tutorial, how can I run examples and build game?
(sorry, I'm not js programmer, but want to try your engine).

**Comment by PerStrateg** [comment]
Because, if I run .html files from games folders - there nothing happens. And there no instruction, how author should compile questjs.

**Comment by ThePix** [comment]
KilianKilmister did some major revisions, which I merged in t see how they work, and now I - like you - cannot get it to work. I am hoping he will respond, but if he does not within a couple of weeks, I will revert to the earlier version, which I know does work and already has a tutorial.

https://github.com/ThePix/QuestJS/pulls?q=is%3Apr+is%3Aclosed

**Comment by PerStrateg** [comment]
https://github.com/ThePix/QuestJS/tree/fd960365601f8778d5f6674afa9fc29e473e98fa this is right link, bebore @KilianKilmister made changes.

**Comment by ThePix** [comment]
I have reverted to the older version.

There is a tutorial here:
https://github.com/ThePix/QuestJS/wiki

**Comment by PerStrateg** [comment]
thx ;)
