### ISSUE TITLE
Keep Getting Error Message

### ISSUE THREAD

**Issue by GameText2020** [ThePix/QuestJS#14]
I read on this page: http://textadventures.co.uk/forum/quest/topic/4451/questjs-update#p29325 that you could use this page: http://questjs.azurewebsites.net/compile to take a Quest game and compile it, but I just keep getting a blue screen with an error message. Also, the tutorial suggested would be helpful.

Thanks!

**Comment by PerStrateg** [comment]
I think that this repo and site are different things.
For QuestJS 6 you need to write your game on pure js. And it's doesn't support Quest 5 files.

**Comment by ThePix** [comment]
That is a different QuestJS, written by someone else. It was in development some years ago, but then abandoned.
