### ISSUE TITLE
Button/link navigation

### ISSUE THREAD

**Issue by PerStrateg** [ThePix/QuestJS#16]
Hi. Is it possible to make game like in twine or coya (only with links) on your engine? 
I mean, don't use console at all, and do operations only with buttons/links?

**Comment by ThePix** [comment]
Yes it is. I have added a quick note about how to do so here:
https://github.com/ThePix/QuestJS/wiki/No-Command-Line

**Comment by PerStrateg** [comment]
Thanks! Looks awesome!)
Your engine should be much more popular. Because it's looks very promising!

**Comment by PerStrateg** [comment]
Oh, I will try to implement some basic demo game with this feature ;)

**Comment by ThePix** [comment]
Cool, I am closing the issue.
