### ISSUE TITLE
io.toggleDarkMode does not update io.textColour (minor)

### ISSUE THREAD

**Issue by Kln95130** [ThePix/QuestJS#24]
This causes the  compass links to return to the black colour when an input is asked (for instance, through a showMenu). This is probably because io.textColour is a variable, and not a getter.

The best solution would be to add `io.textColour = $(".side-panes").css("color");` to the io.toggleDarkMode function, Changing textColour to a getter function would mean accessing the css selector at each call, which is not optimal.

**Comment by ThePix** [comment]
Thanks, now corrected
