### ISSUE TITLE
Problem with language

### ISSUE THREAD

**Issue by DakinQuelia** [ThePix/QuestJS#27]
Hello,

As you said on wiki, the language key not English is an issue for command.

We can't translate the language file to other language. How do to fix it ?

Best regard

**Comment by ThePix** [comment]
To be honest, it was a low priority because I did not think anyone was interested in translating. Give me a few days, and I will see what I can do.

**Comment by DakinQuelia** [comment]
I am interested in being able to translate. 

No problem with few days or weeks. 

Thank you.

**Comment by ThePix** [comment]
That was far easier than I was expecting, and I think potentially better for English too.
https://github.com/ThePix/QuestJS/wiki/The-Language-File#display-verbs

Note: I have uploaded the latest file to Github, but not updated the .zip file yet

**Comment by ThePix** [comment]
By the way, I would appreciate any feedback on how this goes. Anywhere the documentation needs improving or where I have made assumptions that are true in English, but not in other languages.

Even if you do not complete it, a halfway done file might help someone else.

**Comment by ThePix** [comment]
Hi Dakin

How is this going?

I just wanted to flag up that I have made some small changes to lang-en.js for you to be aware of. It is mostly so the message names are all lower case and underscores for consistency; a handful were in camel case, mostly for ropes.

**Comment by DakinQuelia** [comment]
Hello ThePix,

You mean the camel case for variable ?

**Comment by ThePix** [comment]
For example, ropeExamineAddBothEnds has become rope_examine_attached_both_ends. The changes are here:

https://github.com/ThePix/QuestJS/commit/9fd439e6379f4ef9ac50397acebfe7474d45c4fe#diff-60b6fd3e135617cb439ba06ac7788b8c60c326aaf07700f05b959bc3eb6d2fb7
