### ISSUE TITLE
How do we suppress "You can see..." when there is nothing in the current room?

### ISSUE THREAD

**Issue by KVonGit** [ThePix/QuestJS#3]
Hello, Pix!

How do we stop it from printing "You can see..." and/or "You can go..." when the list count is 0?

**Comment by ThePix** [comment]
Hiya

The text processor allows you to do that, and there are instructions on its Wiki page (you could already do it for objects, I have updated it so you can do it for exits too). This:


You can use `exits` and `objects` to get a list of available exists and a list of objects in the current room. These are useful for the room template. There are also "objectsHere" and "exitsHere" directives that you can wrap the whole thing in so "You can see" only appears if there is actually something here.
```
const ROOM_TEMPLATE = [
  "%",
  "{exitsHere:You can go {exits}.}",
  "{objectsHere:You can see {objects} here.}",
]
```
