### ISSUE TITLE
Making an object not visible?

### ISSUE THREAD

**Issue by KVonGit** [ThePix/QuestJS#30]
Is there a built-in way to make an object invisible?

In Quest 5, we could set ```visible``` to ```false```, but I can't find anything that does that in this code.

I cheated like this:

```js
createItem("destinations",{
	loc:"hub",
	examine:()=>metamsg(`You can't see that.`),
	scenery:true,
	excludeFromAll:true,
	take:()=>metamsg(`You can't see that.`)
});
```

---
If there's a legitimate method, I'd rather not hack.  Else, it's no big deal.  This is one of the few times I'd want to do this anyway.

**Comment by ThePix** [comment]
You can always delete the line:
```
loc:"hub",
```
Why would you want it to be in the location, but not visible?

**Comment by KVonGit** [comment]
> Why would you want it to be in the location, but not visible?

I don't remember what we did with that ```destinations``` object in the Quest Group Project.

I'm just trying to port that main game and library over to the new stuff.

I already have a haphazard way to send data from game to game via url, mostly based on your old code from different places.

I think we'd have to fake the newly added exits to different "dimensions".  I'm thinking of cloning a fake exit object, making the name something like "exit to the north".  Then, hijacking the GO NORTH command in that room so it actually loads a url to a new game while transferring some attribute data along the way.

Digressions aside, I was just copying your old objects and such from the group project.  That ```destinations``` object was marked ```visible=false```, and I began to search for such a setting in the new Quest code.

It's no big deal at all.  I figured out how to fake it, and I may not even use it.  I just wanted to make sure I wasn't overlooking anything.

**Comment by ThePix** [comment]
> I already have a haphazard way to send data from game to game via url, mostly based on your old code from different places.

There is a help page about this, but it assumes the game is hosted as a web page, rather than on textadventures
https://github.com/ThePix/QuestJS/wiki/Chaining-Several-Games-Together
