### ISSUE TITLE
[Add function] Function CreatePaneBox()

### ISSUE THREAD

**Issue by DakinQuelia** [ThePix/QuestJS#31]
Hello,

I've created a little function to make a pane box : 

```
function createPaneBox(position, title, content) 
{
    $("div.pane-div:nth-child(" + position + ")").before('<div class="pane-div"><h4 class="side-pane-heading">' + title + '</h4><div class="pane-content">' + content + '</div></div>');
}
```

Example :

```
createPaneBox(2, "Mon test", "Blabla")
```

Picture in next post.

Best regards

**Comment by DakinQuelia** [comment]
![01](https://user-images.githubusercontent.com/420018/101307420-b4acf780-3847-11eb-9a1a-a7d7bb99cd50.png)

**Comment by DakinQuelia** [comment]
![02](https://user-images.githubusercontent.com/420018/101307826-a9a69700-3848-11eb-90f9-0bcb76a1b72b.png)

**Comment by DakinQuelia** [comment]
![03](https://user-images.githubusercontent.com/420018/101308182-8c25fd00-3849-11eb-9ddf-305610cbf91e.png)

**Comment by ThePix** [comment]
Thanks. It had crossed my mind that something like this would be useful. It is in the latest upload.

**Comment by ThePix** [comment]
Documentation added:
 https://github.com/ThePix/QuestJS/wiki/Additional-Side-Pane
