### ISSUE TITLE
BUG REPORT and fix(?) - Error when trying to throw an error from line 296 in parser.js

### ISSUE THREAD

**Issue by KVonGit** [ThePix/QuestJS#33]
https://github.com/ThePix/QuestJS/blob/e3b597416c252ed9c2a08dcb5f10d026724d58da/lib/_parser.js#L296

Existing: ```res.error = no_multiples_msg;```

What works for me:  ```res.error = lang.no_multiples_msg;```

---
I just noticed the same thing on line 314 as well.

Cheers!

**Comment by ThePix** [comment]
Fixed, thanks
