### ISSUE TITLE
[Suggestion] Move certain folders

### ISSUE THREAD

**Issue by DakinQuelia** [ThePix/QuestJS#41]
Hello,

To better reorganize the game's folder, some folders should be moved into a new folder named "assets". The ressources (sounds/images/icons) to move to "assets".

Best regards

**Comment by DakinQuelia** [comment]
Any example :

![folders](https://user-images.githubusercontent.com/420018/102035159-07466080-3dc0-11eb-80f5-b1e37b8273f4.png)

**Comment by ThePix** [comment]
Good idea. Latest upload to Github does it.
