### ISSUE TITLE
log and debuglog

### ISSUE THREAD

**Issue by KVonGit** [ThePix/QuestJS#43]
Hello.

Here's an easy one, and I believe you'll like the idea.

How about including a ```log``` and a ```debuglog``` (and maybe a ```parserlog```, just to fit the rhyme scheme)?

```js
const log = console.log
const debuglog = (s) => { if(settings.playMode === 'dev' || settings.playMode === 'meta'){ log(s)} }
const parserlog = (s) => { if(parser.debug){ log(s)} }
```

---
If not, that's cool, too.  It wouldn't hurt my feelings at all.

**Comment by ThePix** [comment]
Done, because ~i got sick of typing console.log. Some JS purists will say we are polluting the name space, but so be it.
