### ISSUE TITLE
BUG (and fix?) - handlePutInContainer

### ISSUE THREAD

**Issue by KVonGit** [ThePix/QuestJS#46]
https://github.com/KVonGit/Quest6Game1/blob/47c170c65174b4374d705c4028a2a03770e6a3ae/lib/_commands.js#L1325

```js
    failedmsg(lang.not_container(char, container));
```

---
I changed that to this:

```js
    failedmsg(lang.not_container, {char, container});
```

---
Also, in related news:

https://github.com/KVonGit/Quest6Game1/blob/47c170c65174b4374d705c4028a2a03770e6a3ae/lang/lang-en.js#L198

This is the only line I find the word 'containter'.

**Comment by ThePix** [comment]
Fixed, thanks
