### ISSUE TITLE
JSDoc (not an issue)

### ISSUE THREAD

**Issue by KVonGit** [ThePix/QuestJS#48]
Hello.

Check out what I've done with JSDoc and jsdoc-to-markdown:

https://github.com/KVonGit/Item-Links-Library/wiki/Documentation

---
I still have lots of things to add to this, by the way.

---
I've created a new repo just for this library:

https://github.com/KVonGit/Item-Links-Library

The file itself:
https://github.com/KVonGit/Item-Links-Library/blob/main/item_links.js

---
I saw you had ```@DOC``` and ```@UNDOC``` in your comments, wondered what the heck that was for, and here we are.

---
NOTE

Feel free to close this issue once you've read this.  I started to close it as soon as I submitted this, but I wasn't sure you'd be notified of its existence that way.

**Comment by KVonGit** [comment]
Here's a link to the website created by JSDoc (it's easier to navigate):

http://media.textadventures.co.uk/games/xWsX6D9IyU6fRwyprp7HDA/index.html

**Comment by ThePix** [comment]
I actually wrote my own JSDoc-look-alike, to get it to do exactly what I wanted.
https://github.com/ThePix/PixDocs

**Comment by KVonGit** [comment]
That one looks much easier to deal with.  I'll have to check that out.

...as soon as Pertex finishes exterminating my current code.  (He is keeping me quite busy at the moment.  I have many instances of "thanks to Pertex" in the version changes file. Pertex is pretty damn cool.)
