### ISSUE TITLE
NPC Entering Message When Dark

### ISSUE THREAD

**Issue by KVonGit** [ThePix/QuestJS#49]
Hello.

What would be the proper way to stop the entering message on my NPCs when in a dark room?

(Right now, if ```game.dark```, I have it skipping everything.)

**Comment by ThePix** [comment]
I am trying to think the best way to do this. What do you _want_ to happen? 

Do you want the player to get a message; "You hear someone enter the room." If so, would that depend on the NPC - you do not hear the ninja for example? Would it depend on the room? If yes to either of these, where would you want to put the strings?

**Comment by KVonGit** [comment]
> What do you want to happen?

A very good question.

> would that depend on the NPC - you do not hear the ninja for example? Would it depend on the room? If yes to either of these, where would you want to put the strings?

Ooh!  A can of worms!

I don't think we should open this particular can.  Maybe there could be something like the name modifier added on that the author could script if the need was felt.  The NPC reporting function could check that in the dark.  If nothing is coded, just do nothing.  (Maybe?)

I don't know, but it didn't seem quite right that the game reported the NPC entering when I couldn't see in the dark.  Maybe I'm just over-thinking it.

---
Hey . . .

What if there was an NPC who could see in the dark, and he described things for you after entering?

(The ninja is a good example, too.)

Maybe just a boolean to put on settings that tells Quest whether or not to report NPCs entering in the dark would be easiest?

**Comment by KVonGit** [comment]
I think this would be a good one for the forum, letting everyone have a chance to propose scenarios.

What say you?

**Comment by ThePix** [comment]
That's a good idea.
