### ISSUE TITLE
item_links - Update to 0.10 & PixDocs Doc

### ISSUE THREAD

**Issue by KVonGit** [ThePix/QuestJS#50]
Hello.

Gift 1:  https://github.com/KVonGit/Item-Links-Library/wiki/PixDocs-Doc#item-links-lib

---
Gift 2: https://github.com/KVonGit/Item-Links-Library/blob/main/item_links.js

This includes a mod of ```io.finish``` which disables all item, exit, and command links.

Also, the comments have been PixDocs-ified (as is obviously obvious to you, no doubt).

I also got rid of ```enterButtonPress``` code, and used ```runCmd``` in its place.

---
Merry Christmas to all, and to all a good night!

**Comment by ThePix** [comment]
Just so you know, I slightly modified the link-library. See here:
https://github.com/ThePix/QuestJS/issues/51

**Comment by KVonGit** [comment]
> Just so you know, I slightly modified the link-library

Whoops!

Got it.  Updated that line on my end too,

---
This is the most up-to-date file (contains quite a few fixes for issues I discovered in the version you have):

[KVonGit/Item-Links-Library/blob/main/item_links.js](https://github.com/KVonGit/Item-Links-Library/blob/main/item_links.js)
