### ISSUE TITLE
Change from page.html to index.html

### ISSUE THREAD

**Issue by KVonGit** [ThePix/QuestJS#56]
Hello.

I think I understand why this was changed.  It was probably because twitch.io wants to find a file called "index.html" to target.  (This is pure conjecture based upon my experiences with other sites to which I've posted games in the form of websites.)

This sort of messes up the way I do my landing page, though.  It's not really a big issue, as I can just change the name of the file back to "page.html" in my directory I copy from before creating a new game.  But . . .

I don't really know if this is the standard, but the IF Archive and the textadventures site both seem to be set up to load "index.html" whenever it exists.  This means I can have a landing page named "index.html" and a game file named "play.html" or "page.html" in my directory, and my landing page will definitely be the starting page.

Alternatively, if there is no "index.html", the site will load "play.html"  or "page.html" (or I guess if there's only one page in the main directory it loads that).

I am not sure this is the standard, but, if it is, I would think "play.html" might be a better name *IF* twitch.io will load that as the starting page when there is no index.html.

I sent a "Contact us" message to the textadventures site asking if this was the standard or if the site was just set up this way to handle the website files put out by Inform 7, but that was a few days and no response has arrived as of yet.

---
Again, this is no big deal as far as I'm concerned.  I can easily change that file's name one time and not have to worry with it until the next update to Quest 6.  I know you're trying to make it as easy as possible for everyone to use, though.  So, I thought I'd chime in on this.

**Comment by ThePix** [comment]
It was Itch.io that persuaded me to do this; I could see no alternatives.

index.html is the standard generally on the web, by the way.
