### ISSUE TITLE
OMG, Pixie! I loved your Startopia mods!

### ISSUE THREAD

**Issue by plumskit** [ThePix/QuestJS#59]
Hello The Pixie,
Please, don't delete this message for being off-topic, I've tried to contact you at various points in the last 17 years, through that Thief TTLG forums and what not, and Github is the only way I found.

Back in 2004 I discovered the Startopia modding community, I played every single mods I could find, your mods were in a league of their own for their brilliant mix of challenge, narrative and uniqueness, like that Cosmic Balance mission where you got to develop the station with that new age, feng shui, karma balance philosophy, that Scratch mission where you got to build that huge station from scratch because there are no traders, that XenSoc mission where VAL gets rebooted, or that Lest We Forget mission on a haunted space station where the opening ceremony went fire and fury unless you completed that secret objective of exorcising the ghost (that one was a masterpiece!)

You were lightyears ahead of other modders, dude, had your mods been released during the peak of the Startopia community I am sure you would have inspired a tons of modders to strive for that mix of unique gameplay feature and story telling.

Back in 2005, when Startopia websites started to go offline due to inactivity, I got in contact with a dude by the name of MaxOoze who was on a quest to find all Startopia content and host it on a site of his own to keep them alive. I had your missions so I sent them to him. Sometimes in 2012, GOG.com and Steam added Startopia to their catalog so I linked MaxOoze's site on their forums, with a rundown of the mods so a new generation of Startopia fans could discover your mods. And now that MaxOoze's website has gone offline, I have taken upon myself to create a website of my own to host all the Startopia mods out there to keep them alive.

The site is not online right now, a friend of mine is proof reading it at the moment, if all goes well I'll upload it this saturday, but all these years I wanted to tell you that:

Your missions were phenomenal, the best Startopia mods I had the pleasure of playing.

I wanted to ask you if you still had backups of the original files of your Startopia mods. I have copies of your four mods, but they have been edited by me, back in the days, when I came across a typo I edited the mission file to fix them, and I also wanted my mission folder to be sorted by author, so I renamed all the mission folders and I also had to edit all the mission files to reflect this new folder name. Back then I didn't know those files would become the last surviving copies of some of these mods. I managed to hunt down the original version of most Startopia mods, but I couldn't find original versions of yours. (If you have backup of Startopia modding guides or tools, I'd take them too because I am missing some also.)

And I wanted to ask you if you had a secret unreleased fifth mod up your sleeve or something, because I recall that everytime you posted a mod on the Startopia forums, you hinted the title of your next mod. And when you released your fourth mod, you hinted that you were already working on a fifth mod. I spend hours wishing that fifth mod saw the light of day, trying to figure out what unique feature you cooked up next, it had "Angels" in the title if my memory serve me right.

That's about it, plz respond, I searched for you for so long ç_ç
You can also contact me at: plumskit@gmail.com
-plumskit

**Comment by ThePix** [comment]
Hi Plumskit

Nice to hear you enjoyed my mods so much! Did they not have my e-mail address in them?

Startopia was a brilliant game that never got the recognition it deserved. I think I came to it a little late, having found it on sale somewhere. it was the first time I had had a go at modding; they were actually relatively simple, and the basic ideas were not that revolutionary. How can no one had thought of having you build everything from scratch already?

I did hope to release a mod for each race, but that never happened, and only got as far as a four. I think Angels would have been  Sirens, but I cannot remember any more about it than that. I do not recall making a start on it.

Somewhere I have a bunch of back-up CDs that probably have the original versions on them. I came across them recently, but now cannot find them, but I will probably find them again in a few weeks!

I did find the missions on someone's web site a few years ago (was it called something station?). It is always weird when your own stuff turns up unexpectedly on someone else's web site.

**Comment by plumskit** [comment]
Thanks for the reply! :D

> Nice to hear you enjoyed my mods so much! Did they not have my e-mail address in them?
There was a Hotmail address but when I tried to contact you I got a "inbox full" or "failure to deliver" message. Gmail spoiled us with that infinite storage space I'm afraid.

> How can no one had thought of having you build everything from scratch already?
There was another one that was very similar to Scratch but at the same time played differently, Scratch gave you reasonable starting supplies but you were on a timer so you had to trudge along. The other mission gave you the bare absolute minimum needed to get you going, build-your-own-scratch basically, but the lack of timer meant once you finally got your head out of the water, it turned into a normal mission where the goal was to research nearly everything.

> they were actually relatively simple, and the basic ideas were not that revolutionary.
The timers helped. Not a lot of mods had timers. I can't speak for others but without a deadline or some sort of fail state, I tend to get into the same routine: First I get the basic needs covered, then I try to amass as much money as possible (typically by trading) and finally I work on the objective. Timers tend to throw a wrench in my build order and make things more interesting.

But Cosmic Balance's karma mechanic was unseen in the game for sure. As for Lest We Forget's secret objective, it came from the left field. When I first played it, I was marathoning the single player campaign and the mods. Thirty missions of "Here's your orders!" and me following them. It threw me for a loop to have a mission with a secret objective hidden in the narrative.

There was another mod that mixed narrative and gameplay, where your employer and Arona had requests that put you at odds with the other, you received different bonuses or penalties depending on who you pleased or displeased, and you got a different ending depending on whom you sided with at the end. Unfortunately, like Lest We Forget, it came on the tail end of the Startopia modding scene. Thus, mixing narrative and gameplay, or having non-linear missions, became somewhat a novelty in Startopia, on account that only two mods dared to explore the concept.

> I did hope to release a mod for each race, but that never happened, and only got as far as a four. I think Angels would have been Sirens, but I cannot remember any more about it than that. I do not recall making a start on it.
It never occurred to me that you were shooting for a one-mission-for-each-race kind of deal, that makes me ponder what you would have come up with for the remaining five races. It's a shame that never happened.

> Somewhere I have a bunch of back-up CDs that probably have the original versions on them. I came across them recently, but now cannot find them, but I will probably find them again in a few weeks!
That's good to hear. Like I said, I have copies of your mods but at some points in the past 17 years, I edited the files because I wanted the folders to be named like, "The Pixie - Scratch" or "The Pixie - Cosmic Balance", and very recently in preparation for the website, I edited the files and folders back to "Scratch" or "Cosmic Balance". And at some points between these two changes, I'm sure I also fixed some typos I stumbled upon. The missions play perfectly fine, I replayed all four recently, but the files are not original and that bugs me.

I would understand if you don't want me to upload your edited files, at the same time I don't want to pressure you to find your back-up CDs.

Whatever you decide, I do hope you find your back-up CDs again. And if you still have your original files, or any other Startopia related files for that matter, drop me an email. Because I want this site to be as complete as possible, but as time goes on, it is slowly dawning on me the amount of content that may be lost forever because it didn't occur to me to download and preserve everything back then.
 
> I did find the missions on someone's web site a few years ago (was it called something station?). 
I am not familiar with that site, I wish I was because maybe it had Startopia related stuff that I am missing right now. The only site I know that had your mods (because I sent them to him) was MaxOoze's defunct Startopia page:
https://web.archive.org/web/20190213135508/http://web.aanet.com.au/~wideopen/wideopen/games/startopia/index.html

> It is always weird when your own stuff turns up unexpectedly on someone else's web site.
What can I say, Startopia was a fun game but also way too short. The modding scene really brought a second life to that game, a treasure trove of new challenges, more deadpan humor, and unique mechanics (or a mix of all three like your mods). I simply cannot envision Startopia without its modding scene after I discovered it, and I certainly don't want these mods to disappear either.

**Comment by plumskit** [comment]
My website is finally online but I have not publicly announced it yet. Here's an exclusive preview, in case you wanted a glimpse before deciding on whether you want me to include your edited missions or not:
https://plantmonster.net/startopia/startopia.html

**Comment by ThePix** [comment]
I am closing this. I have not found the CDs yet, but will keep an eye out!
