### ISSUE TITLE
Various minor errors

### ISSUE THREAD

**Issue by Kln95130** [ThePix/QuestJS#6]
All of these can be fixed by using custom files or updating the functions on setup, so their priority is minor.

_npc.js:_ `agenda.joining()` refers to an inexistant _followerName_ variable. Fix: replace with _leaderName_
 ```
 joining:function(npc, arr) {
    const **leaderName** = arr.shift();
    npc.setLeader(w[**followerName**]);
    this.text(npc, arr);
    return true;
  },
```
_lang-en.js:_ `verbs.use` is not capitalized. This triggers an error when choosing "Use" in the sidebar UI.

_io.js:_ `io.clickToContinueLink` uses a variable named `click_to_continue`. It should use `lang.click_to_continue` instead, or it triggers an error.
```
io.clickToContinueLink = function() {
  msg('<a class="continue" onclick="io.waitContinue()">' + click_to_continue + '</a>');
  io.continuePrintId = io.nextid - 1;
}
```

**Comment by ThePix** [comment]
Thanks for spotting them. I have updated corrected files.

By the way, relating to your third point, the `wait` facility is one area that I hope to improve to make it easier for authors, so may be significantly changed at some point. It is a bit rubbish if you have several together.

**Comment by Kln95130** [comment]
You're welcome.

I think that one of the ways to improve wait is to listen for a key press, in addition of a click, and make the "click to continue" link more visible with CSS such as:
```
.continue { font-weight: bold; color: blue }
.continue:hover { cursor: pointer }
```
