### ISSUE TITLE
Options for moving items

### ISSUE THREAD

**Issue by Wh0Kn0w5** [ThePix/QuestJS#71]
On the wiki, it has the parameters for the moveToFrom function requiring options, the destination and optionally original location of the item being moved.

However, there is nothing on the wiki page that specifies what said "options" have to be for the script to work properly. I also know that previous iterations of Quest JS did not require that parameter for the function to work.

Are we able to get a bit of clarification as to this parameter, as well as a possible example of the function's proper call also added to the wiki as well?

**Comment by ThePix** [comment]
No further feedback, so I am assuming this is revolved satisfactorily.
