### ISSUE TITLE
Error when trying to display character creation window: showModal function is absent.

### ISSUE THREAD

**Issue by Kln95130** [ThePix/QuestJS#73]
Hello. I am trying to have a character creation window, as shown here: https://github.com/ThePix/QuestJS/wiki/Character-Creation

However, I have the following error:
```javascript
Uncaught TypeError: diag.showModal is not a function
    setUpDialog http://127.0.0.1:5500/lib/_settings.js:294
    touch http://127.0.0.1:5500/game/data.js:31
    outputFromQueue http://127.0.0.1:5500/lib/_io.js:916
    unpause http://127.0.0.1:5500/lib/_io.js:865
    onclick http://127.0.0.1:5500/:1
```
The function seems to have been removed at some point, as it is only present as a call in setUpDialog

**Comment by Kln95130** [comment]
I had a hunch, and I checked the Javascript documentation.

This is actually a browser-based issue. showModal is incompatible with Firefox. Is there a way to find an alternative solution for people, players and devs alike, who use this browser?

**Comment by ThePix** [comment]
Thanks for highlighting that issue.

It looks like this is something that Firefox supported, but in an update it was changed so the user has to explicitly allow it, presumable as a security feature. See the compatibility table on this page:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal

One solution would be to send users to [this page](about:config), to accept the risk and continue, and then click "Show all", fine "dom.dialog_element.enabled" and toggle it to "true".

Howewver, that is not ideal! I will look at a better solution.

**Comment by ThePix** [comment]
Turned out to be easy to correct. It now just uses "show" instead of "showModal", and disables/enables the interface itself.

You will need to download the updated files from GotHub as it is not in a release yet.
