### ISSUE TITLE
Tutorial 9 not correct?

### ISSUE THREAD

**Issue by ImaBuggyMess** [ThePix/QuestJS#74]
In tutorial 9, you are supposed to create a charger that charges a torch(?). However, when just copying the code in place, 2 things seem out of place for me. For one, the compartment cannot be closed since the Container(false) prevents it from being closable.

Secondly, there seems to be _possibly_ out of place references to flashlight (or torches, since who charges a **_torch_**), since the game doesn't recognize w.flashlight.loc, but recognizes w.torch.loc. I'm assuming that it has to do something with synonyms, since flashlight would just be another word for torch.

createItem("charger_button", COMPONENT("charger"), {
  examine:"A big red button.",
  alias:"button",
  push:function(options) {
    if (!w.**charger_compartment.closed** || **w.flashlight.loc** !== "charger_compartment") return falsemsg("{pv:char:push:true} the button, but nothing happens.", options)
  },
})

also as well is w.flashlight.power

Cannot be closed, not named flashlight

**Comment by ImaBuggyMess** [comment]
Also not to post another issue again, but the button go to to tutorial 10, someone put an omega symbol (Ω) instead of the number 10 in the button link.

**Comment by ThePix** [comment]
Thanks for pointing out. I have corrected it.
