### ISSUE TITLE
Furniture attributes described in wiki

### ISSUE THREAD

**Issue by thaskef** [ThePix/QuestJS#80]
I just realized the attribute to put what happens when someone lies on a piece of furniture is "reclineon" rather than "onRecline" as it says in the wiki.  (Same goes for sit and stand).

**Comment by ThePix** [comment]
You are right that the Wiki is wrong - I have now updated it. Thanks for letting me know.

When the player types LIE ON COUCH, it is the "reclineon" function that is called, but generally this is best not altered. It will handle checking the action is allowed and changing the posture. Then it will call the "afterPostureOn" function, if it exists. This is the one authors are generally best using to react to the event.
