### ISSUE TITLE
Q5 to QJS Convertor - "Commands" Button is Failing

### ISSUE THREAD

**Issue by Zanderkat** [ThePix/QuestJS#88]
When using the Q5 to QJS Convertor, the script is failing to convert the "Commands" after pasting the full code of my game. It's printing this error message:

`Hmm, something went wrong there. Perhaps you missed part of it. You need everything from "`

Functions, objects, settings, and styles always convert without error. What can I check to determine if the cause of the bug is within the convertor or my game? The error didn't really specify.

**Comment by ThePix** [comment]
Hmm, does that for me too... I will investigate.

**Comment by ThePix** [comment]
Okay, so I have unloaded a new version. the issue was that it was trying to access the first command, and failing if there were none there.

Were you expecting to find some? I have realised it does not do verbs, so that will need to be resolved at some point.

**Comment by Zanderkat** [comment]
The button seems fixed now! I wasn't sure what to expect, but I assumed that the verbs would be transferred to this section.

**Comment by ThePix** [comment]
Yes, verbs should be... I will take a look, but it will take longer to resolve.

**Comment by ThePix** [comment]
I have uploaded to Github a new version (but not a release). See how it goes.

**Comment by Zanderkat** [comment]
I see the verbs now! However, I noticed that a special note was made about the "objects" attribute and all of my verbs have the same code for this:

```
objects:[
    {scope:parser.isHere},
  ]
```

I'm not sure if this is correct and so I thought I'd check.

**Comment by ThePix** [comment]
Good catch, it would be better with "isPresent", so okay for items held or here.

**Comment by Zanderkat** [comment]
I see the change, so I'll go ahead and close the issue.
