### ISSUE TITLE
Q5 to QJS Convertor: Operator Mistranslations

### ISSUE THREAD

**Issue by Zanderkat** [ThePix/QuestJS#91]
When an if statement includes multiple conditions, an operator is not translated properly after it appears for the first time in that statement. For instance, the following:

`if (John.parent = Apartments and Bob.parent = Apartments and Bob.buddy = false and John.buddy = false)`

...will become:

`if (John.loc === Apartments && Bob.loc = Apartments and Bob.buddy = false and John.buddy = false)`

This doesn't seem to happen with the "!==" operator, which seems to translate properly in all of the instances I've seen. All other operators appear to be affected, however.

On a related note that may or may not help with finding the issue, the convertor translates all instances of "&" into "&&", even if they are in something like a comment.

**Comment by ThePix** [comment]
I think I have fixed this (slightly worried about false positives but should be good). Surprisingly simple to fix.

**Comment by Zanderkat** [comment]
I haven't found any further issues here but I'll keep an eye out!
